# AirBnB base workflow
This notebook is intended to collate AirBnB data split across several files (split by date). Additionally, the notebook has been set up to be compatible with 'run all cells' to get the desired output table.

Version history:

Initial release by Arnold on 6-Aug-26; ready for review

# Instructions
Download listing.csv files from https://insideairbnb.com/get-the-data/ for New Zealand, but label them with the following filename convention:

listing-X.csv

Where X is a serially increasing number starting from 0 for the NEWEST file. Save the csv files to a folder named 'data' located on the root of the project.

IMPORTANT: refer to the companion "AirBnB_date_lookup.csv" file to make sure the file names are aligned with the dates listed. Unfortunately, this is a manual process as scraping the webpage is too much effort for this project.

In [1]:
# Preparing imports
import pandas as pd

In [14]:
#pip install missingno

In [2]:
# Checking lookup table

# Importing the date lookup table
lookup = pd.read_csv("../output_data/AirBnB_date_lookup.csv")
lookup

             name year_month
0  listings-0.csv     2026-6
1  listings-1.csv     2026-5
2  listings-2.csv     2026-4
3  listings-3.csv     2026-3
4  listings-4.csv     2026-2
5  listings-5.csv     2026-1
6  listings-6.csv    2025-12
7  listings-7.csv    2025-11
8  listings-8.csv    2025-10

In [3]:
# Preparing loop to go through all the files in the lookup list and extract all the Chch entries and add them to a single df

# First, initialising empty object to append data to
merged_data = []

# Actual loop over the files and appending chch data to the object
for row in lookup.itertuples(index = False): # using itertuples to go over rows instead of cols (the default)
    df = pd.read_csv(f"../data/{row.name}") # getting the file name from the lookup table
    df = df[df["neighbourhood_group"] == "Christchurch City"]
    df["year_month"] = row.year_month # getting year-month from the lookup table
    merged_data.append(df)

# Finally merging via concat
merged_data = pd.concat(merged_data, ignore_index = True)

merged_data

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,year_month
0,968224198043666870,Room,516048910.0,Heer,Christchurch City,Innes Ward,-43.498150,172.650540,Private room,64.0,1.0,0,NaN,NaN,1.0,89,0,NaN,2026-6
1,24742386,Garden Studio With Ensuite (Breakfast included),43654083.0,Kathy,Christchurch City,Papanui Ward,-43.504070,172.596070,Entire home/apt,172.0,1.0,205,2026-05-19,2.31,1.0,241,36,NaN,2026-6
2,1654821509215926144,Papanui Oasis Entire House,754856789.0,Jonathan Allan,Christchurch City,Papanui Ward,-43.489540,172.614080,Entire home/apt,230.0,1.0,5,2026-05-16,2.24,1.0,335,5,NaN,2026-6
3,7403587,Warm Cosy Quiet Home Semi Rural,38795211.0,Wendy,Christchurch City,Halswell Ward,-43.576050,172.546860,Private room,143.0,1.0,0,NaN,NaN,1.0,263,0,NaN,2026-6
4,22570965,One Bedroom Apartment,44728588.0,Anita Marie,Christchurch City,Papanui Ward,-43.486060,172.616880,Hotel room,202.0,1.0,3,2022-04-27,0.03,6.0,342,0,NaN,2026-6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28790,1161213044338512029,Bright & Airy on Tuam - 2 Beds Apartment,202585247.0,Ohana,Christchurch City,Central Ward,-43.535478,172.635144,Entire home/apt,147.0,1.0,133,2025-10-01,7.95,121.0,35,90,NaN,2025-10
28791,1180667042629129011,Central city sunsets - Warm! Modern! Quiet!,482671075.0,Paula Corinne,Christchurch City,Central Ward,-43.537523,172.638452,Entire home/apt,268.0,1.0,49,2025-09-24,3.15,124.0,285,42,NaN,2025-10
28792,1424846609710116983,Upper floor studio 1 bed 1 bath with sofa bed,482671075.0,Paula Corinne,Christchurch City,Central Ward,-43.537800,172.641679,Entire home/apt,126.0,1.0,17,2025-09-27,3.75,124.0,239,17,NaN,2025-10
28793,1395109904560781257,Cozy guesthouse in casebrook,433251428.0,Donna,Christchurch City,Harewood Ward,-43.478480,172.602470,Entire home/apt,102.0,1.0,3,2025-08-16,0.51,1.0,160,3,NaN,2025-10
28794,1051269971528217000,Spacious and Tranquil 4 Bed House Near UC,49642171.0,Xihang,Christchurch City,Riccarton Ward,-43.518466,172.570730,Entire home/apt,211.0,1.0,45,2025-07-10,2.16,88.0,133,20,NaN,2025-10

In [4]:
# Finally exporting the csv out back to ../data
merged_data.to_csv("../data/AirBnB_all_chch.csv", index = False)